import {
  Customer,
  BankAccount,
  Card,
  Transaction,
  AuditLog,
  Employee,
  Branch,
  ATM,
  Loan,
  NotificationItem,
  SupportTicket,
} from "../types";
import { predictFraudRandomForest } from "./fraudEngine";

export const initialCustomers: Customer[] = [
  {
    id: "CUST-1001",
    name: "Vikramaditya Rao",
    aadhaar: "8492-1102-9921",
    pan: "ABCDE1234F",
    address: "702 Jubilee Hills, Hyderabad, TS 500033",
    email: "vikramaditya.rao@bankguard.ai",
    mobile: "+91 98765 11001",
    dob: "1985-04-12",
    occupation: "Chief Information Security Officer",
    annualIncome: 350000,
    customerType: "HNWI",
    kycStatus: "Verified",
    creditScore: 820,
    riskScore: 12,
    isFrozen: false,
    linkedAccountsCount: 3,
    avatarUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    documents: [
      { name: "Aadhaar_Card_Copy.pdf", type: "Identity", date: "2025-01-10", status: "Verified" },
      { name: "PAN_Card_Copy.pdf", type: "TAX", date: "2025-01-10", status: "Verified" },
      { name: "W2_Income_Proof.pdf", type: "Income", date: "2025-01-12", status: "Verified" },
    ],
  },
  {
    id: "CUST-1002",
    name: "Dr. Rajesh Mehta",
    aadhaar: "9912-4410-3304",
    pan: "FGHIJ5678K",
    address: "42 Bandra Kurla Complex, Mumbai, MH 400051",
    email: "rajesh.mehta@bankguard.ai",
    mobile: "+91 98765 22002",
    dob: "1982-09-24",
    occupation: "Head of Fraud SecOps",
    annualIncome: 280000,
    customerType: "Corporate",
    kycStatus: "Verified",
    creditScore: 795,
    riskScore: 18,
    isFrozen: false,
    linkedAccountsCount: 2,
    avatarUrl:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    documents: [
      { name: "Passport_Scan.pdf", type: "Identity", date: "2025-02-01", status: "Verified" },
      { name: "Utility_Bill_Address.pdf", type: "Address", date: "2025-02-01", status: "Verified" },
    ],
  },
  {
    id: "CUST-1003",
    name: "Harsh Ganeshwade",
    aadhaar: "1102-9981-1198",
    pan: "KLMNO9012P",
    address: "88 Cyber City, Sector 29, Gurugram, HR 122002",
    email: "harshganeshwade@gmail.com",
    mobile: "+91 98765 33003",
    dob: "1996-11-05",
    occupation: "Principal Systems Engineer",
    annualIncome: 240000,
    customerType: "Individual",
    kycStatus: "Verified",
    creditScore: 810,
    riskScore: 8,
    isFrozen: false,
    linkedAccountsCount: 4,
    avatarUrl:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    documents: [
      { name: "Aadhaar_Verified.pdf", type: "Identity", date: "2025-01-15", status: "Verified" },
      { name: "TAX_Return_2025.pdf", type: "TAX", date: "2025-01-15", status: "Verified" },
    ],
  },
  {
    id: "CUST-1004",
    name: "Priya Sharma",
    aadhaar: "7721-8812-4402",
    pan: "QRSTU3456V",
    address: "12 Connaught Place, New Delhi, DL 110001",
    email: "priya.sharma@gmail.com",
    mobile: "+91 98765 43210",
    dob: "1993-03-15",
    occupation: "E-Commerce Director",
    annualIncome: 190000,
    customerType: "Individual",
    kycStatus: "Verified",
    creditScore: 775,
    riskScore: 22,
    isFrozen: false,
    linkedAccountsCount: 2,
    avatarUrl:
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    documents: [
      { name: "Aadhaar_Verified.pdf", type: "Identity", date: "2025-01-05", status: "Verified" },
    ],
  },
  {
    id: "CUST-1005",
    name: "Ananya Verma",
    aadhaar: "5512-3390-8811",
    pan: "WXYZA7890B",
    address: "104 Koregaon Park, Pune, MH 411001",
    email: "ananya.verma@outlook.com",
    mobile: "+91 91234 56789",
    dob: "1997-08-30",
    occupation: "Financial Analyst",
    annualIncome: 160000,
    customerType: "HNWI",
    kycStatus: "Verified",
    creditScore: 780,
    riskScore: 91,
    isFrozen: true,
    linkedAccountsCount: 3,
    avatarUrl:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    documents: [
      { name: "KYC_Reverification_Doc.pdf", type: "Audit", date: "2025-02-05", status: "Flagged" },
    ],
  },
];

export const initialAccounts: BankAccount[] = [
  {
    id: "ACC-8921",
    accountNumber: "4592-0012-8921",
    customerId: "CUST-1001",
    customerName: "Vikramaditya Rao",
    type: "Savings",
    balance: 142850.0,
    currency: "INR",
    status: "Active",
    createdAt: "2023-05-14",
    branchName: "Cyber City Main",
    linkedCardCount: 2,
  },
  {
    id: "ACC-3304",
    accountNumber: "9921-4401-3304",
    customerId: "CUST-1002",
    customerName: "Dr. Rajesh Mehta",
    type: "Current",
    balance: 38200.5,
    currency: "INR",
    status: "Active",
    createdAt: "2024-01-20",
    branchName: "BKC Financial Tower",
    linkedCardCount: 1,
  },
  {
    id: "ACC-1198",
    accountNumber: "1102-8812-1198",
    customerId: "CUST-1003",
    customerName: "Harsh Ganeshwade",
    type: "Salary",
    balance: 512900.0,
    currency: "INR",
    status: "Active",
    createdAt: "2022-11-10",
    branchName: "Cyber City Main",
    linkedCardCount: 3,
  },
  {
    id: "ACC-4402",
    accountNumber: "7721-3302-4402",
    customerId: "CUST-1004",
    customerName: "Priya Sharma",
    type: "Savings",
    balance: 85400.0,
    currency: "INR",
    status: "Active",
    createdAt: "2023-09-02",
    branchName: "Connaught Place",
    linkedCardCount: 1,
  },
  {
    id: "ACC-8811",
    accountNumber: "5512-9901-8811",
    customerId: "CUST-1005",
    customerName: "Ananya Verma",
    type: "Current",
    balance: 18400.0,
    currency: "INR",
    status: "Frozen",
    createdAt: "2021-06-18",
    branchName: "Koregaon Park",
    linkedCardCount: 2,
  },
];

export const initialCards: Card[] = [
  {
    id: "CARD-4492",
    cardNumber: "4532-XXXX-XXXX-4492",
    customerName: "Vikramaditya Rao",
    customerId: "CUST-1001",
    accountNumber: "4592-0012-8921",
    type: "Credit",
    isBlocked: false,
    expiry: "10/28",
    creditLimit: 50000,
    currentSpend: 12450,
    pinResetRequested: false,
  },
  {
    id: "CARD-1105",
    cardNumber: "5412-XXXX-XXXX-1105",
    customerName: "Ananya Verma",
    customerId: "CUST-1005",
    accountNumber: "5512-9901-8811",
    type: "Debit",
    isBlocked: true,
    expiry: "04/27",
    creditLimit: 0,
    currentSpend: 0,
    pinResetRequested: true,
  },
  {
    id: "CARD-7732",
    cardNumber: "4111-XXXX-XXXX-7732",
    customerName: "Dr. Rajesh Mehta",
    customerId: "CUST-1002",
    accountNumber: "9921-4401-3304",
    type: "Credit",
    isBlocked: false,
    expiry: "12/29",
    creditLimit: 25000,
    currentSpend: 4200,
    pinResetRequested: false,
  },
  {
    id: "CARD-2290",
    cardNumber: "4000-XXXX-XXXX-2290",
    customerName: "Harsh Ganeshwade",
    customerId: "CUST-1003",
    accountNumber: "1102-8812-1198",
    type: "Debit",
    isBlocked: false,
    expiry: "08/28",
    pinResetRequested: false,
  },
];

// Helper to generate realistic transactions
const sampleFeatures1 = {
  amount: 15400,
  timeHour: 2,
  dayOfWeek: 4,
  merchantCategory: "Offshore Crypto Exchange",
  location: "Kolkata, WB",
  deviceId: "DEV-UNKNOWN-99",
  ipAddress: "192.168.1.105",
  prevTransactions24h: 8,
  transactionFrequency: 4.5,
  avgDailySpend: 400,
  failedLoginAttempts: 4,
  distanceKm: 2400,
  loginDeviceChanged: true,
  cardPresent: false,
  velocityScore: 92,
  beneficiaryAgeDays: 0,
  isNewDevice: true,
  isVpnUsed: true,
  isAtmWithdrawal: false,
  isCashDeposit: false,
};

const pred1 = predictFraudRandomForest(sampleFeatures1);

const sampleFeatures2 = {
  amount: 4850,
  timeHour: 10,
  dayOfWeek: 2,
  merchantCategory: "Wire Transfer",
  location: "Guwahati, AS",
  deviceId: "DEV-MAC-402",
  ipAddress: "91.240.118.12",
  prevTransactions24h: 3,
  transactionFrequency: 1.5,
  avgDailySpend: 300,
  failedLoginAttempts: 2,
  distanceKm: 2800,
  loginDeviceChanged: true,
  cardPresent: false,
  velocityScore: 85,
  beneficiaryAgeDays: 1,
  isNewDevice: true,
  isVpnUsed: true,
  isAtmWithdrawal: false,
  isCashDeposit: false,
};

const pred2 = predictFraudRandomForest(sampleFeatures2);

export const initialTransactions: Transaction[] = [
  {
    id: "TX-9102-F",
    txId: "TX-9102-F",
    timestamp: "10:41:55 UTC",
    customerId: "CUST-1005",
    customerName: "Vikramaditya Rao",
    accountNumber: "5512-9901-8811",
    destination: "Offshore Crypto Exch",
    type: "Transfer",
    amount: 15400.0,
    status: "Pending Review",
    riskScore: pred1.riskScore,
    fraudProbability: pred1.fraudProbability,
    riskCategory: pred1.riskCategory,
    isFlagged: true,
    recommendedAction: pred1.recommendedAction,
    primaryReason: "Large transfer from new device in Kolkata, WB (+ VPN)",
    features: sampleFeatures1,
    shapExplanations: pred1.featureImportance,
    investigatorNotes:
      "Multiple failed logins recorded from IP 192.168.1.105 right before high-value outbound transfer.",
    assignedInvestigator: "Pending Assignment",
    isReviewed: false,
  },
  {
    id: "TX-2049-INV",
    txId: "TX-2049-INV",
    timestamp: "10:40:12 UTC",
    customerId: "CUST-1001",
    customerName: "Marcus Chen",
    accountNumber: "4592-0012-8921",
    destination: "CryptoEx Global",
    type: "Transfer",
    amount: 4850.0,
    status: "Hold",
    riskScore: pred2.riskScore,
    fraudProbability: pred2.fraudProbability,
    riskCategory: pred2.riskCategory,
    isFlagged: true,
    recommendedAction: pred2.recommendedAction,
    primaryReason: "High velocity + Foreign IP + New Device",
    features: sampleFeatures2,
    shapExplanations: pred2.featureImportance,
    investigatorNotes: "Case #INV-2049 opened. Requires immediate SMS customer callback.",
    assignedInvestigator: "Sarah Connor (Lead Auditor)",
    isReviewed: true,
  },
  {
    id: "TX-8924-A",
    txId: "TX-8924-A",
    timestamp: "10:42:01 UTC",
    customerId: "CUST-1001",
    customerName: "Marcus Chen",
    accountNumber: "4592-0012-8921",
    destination: "Amazon WS Services",
    type: "UPI",
    amount: 124.5,
    status: "Cleared",
    riskScore: 12,
    fraudProbability: 12,
    riskCategory: "Safe",
    isFlagged: false,
    recommendedAction: "Approve Transaction",
    primaryReason: "Standard merchant interaction",
    features: {
      amount: 124.5,
      timeHour: 10,
      dayOfWeek: 3,
      merchantCategory: "Cloud Hosting",
      location: "Mumbai, MH",
      deviceId: "DEV-MARCUS-IPHONE",
      ipAddress: "68.12.44.10",
      prevTransactions24h: 1,
      transactionFrequency: 1.0,
      avgDailySpend: 500,
      failedLoginAttempts: 0,
      distanceKm: 0,
      loginDeviceChanged: false,
      cardPresent: true,
      velocityScore: 10,
      beneficiaryAgeDays: 500,
      isNewDevice: false,
      isVpnUsed: false,
      isAtmWithdrawal: false,
      isCashDeposit: false,
    },
    shapExplanations: [
      { featureName: "Trusted Merchant", contributionPercent: -15, reasonText: "Frequent billing history", impactType: "mitigating" },
      { featureName: "Known Device", contributionPercent: -10, reasonText: "Registered primary phone", impactType: "mitigating" },
    ],
  },
  {
    id: "TX-8845-W",
    txId: "TX-8845-W",
    timestamp: "10:38:12 UTC",
    customerId: "CUST-1002",
    customerName: "Elena Jenkins",
    accountNumber: "9921-4401-3304",
    destination: "ATM #Reg-4 (Bengaluru Whitefield)",
    type: "ATM",
    amount: 500.0,
    status: "Cleared",
    riskScore: 48,
    fraudProbability: 48,
    riskCategory: "Medium Risk",
    isFlagged: false,
    recommendedAction: "Allow with SMS alert to cardholder",
    primaryReason: "First time ATM withdrawal in new branch region",
    features: {
      amount: 500,
      timeHour: 10,
      dayOfWeek: 3,
      merchantCategory: "ATM Withdrawal",
      location: "Bengaluru, KA",
      deviceId: "ATM-REG-4",
      ipAddress: "10.4.12.90",
      prevTransactions24h: 2,
      transactionFrequency: 1.5,
      avgDailySpend: 300,
      failedLoginAttempts: 0,
      distanceKm: 45,
      loginDeviceChanged: false,
      cardPresent: true,
      velocityScore: 35,
      beneficiaryAgeDays: 100,
      isNewDevice: false,
      isVpnUsed: false,
      isAtmWithdrawal: true,
      isCashDeposit: false,
    },
    shapExplanations: [
      { featureName: "ATM Out of Routine Range", contributionPercent: 18, reasonText: "45km distance from home address", impactType: "medium_risk" },
    ],
  },
  {
    id: "TX-8711-A",
    txId: "TX-8711-A",
    timestamp: "10:35:44 UTC",
    customerId: "CUST-1003",
    customerName: "Samuel Thompson",
    accountNumber: "1102-8812-1198",
    destination: "Payroll Direct Corp",
    type: "NEFT",
    amount: 3250.0,
    status: "Cleared",
    riskScore: 5,
    fraudProbability: 5,
    riskCategory: "Safe",
    isFlagged: false,
    recommendedAction: "Approve Transaction",
    primaryReason: "Verified recurring monthly payroll credit",
    features: {
      amount: 3250,
      timeHour: 10,
      dayOfWeek: 3,
      merchantCategory: "Payroll Direct",
      location: "Chennai, TN",
      deviceId: "DEV-SAMUEL-MAC",
      ipAddress: "12.189.4.11",
      prevTransactions24h: 1,
      transactionFrequency: 0.8,
      avgDailySpend: 800,
      failedLoginAttempts: 0,
      distanceKm: 0,
      loginDeviceChanged: false,
      cardPresent: false,
      velocityScore: 5,
      beneficiaryAgeDays: 900,
      isNewDevice: false,
      isVpnUsed: false,
      isAtmWithdrawal: false,
      isCashDeposit: false,
    },
    shapExplanations: [
      { featureName: "Verified Corporate ACH", contributionPercent: -20, reasonText: "Matches payroll schedule", impactType: "mitigating" },
    ],
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: "AUD-991",
    timestamp: "2026-08-06 14:32:01.055",
    username: "Admin_01",
    role: "Admin",
    ip: "192.168.1.45",
    browser: "Chrome 122.0 / macOS",
    device: "MacBook Pro M3",
    action: "Account Frozen",
    previousValue: "Status: Active",
    newValue: "Status: Frozen (Reason: Fraud Investigation #2049)",
    riskTag: "CRITICAL",
  },
  {
    id: "AUD-990",
    timestamp: "2026-08-06 14:28:45.112",
    username: "System_Auto",
    role: "Admin",
    ip: "10.0.0.1 (Internal Service)",
    browser: "Node.js / Express Service",
    device: "Cloud Container #102",
    action: "Daily Batch Sync Completed",
    previousValue: "Sync State: Pending",
    newValue: "Sync State: Success (24,592 records updated)",
    riskTag: "ROUTINE",
  },
  {
    id: "AUD-989",
    timestamp: "2026-08-06 14:15:22.884",
    username: "Mgr_04_Bengaluru",
    role: "Manager",
    ip: "10.0.5.212",
    browser: "Edge 121.0 / Windows 11",
    device: "Workstation-DT-99",
    action: "Password Changed",
    previousValue: "Hash: Argon2id$v=19$m=65536...",
    newValue: "Hash: Argon2id$v=19$m=65536... (Updated)",
    riskTag: "ELEVATED",
  },
  {
    id: "AUD-988",
    timestamp: "2026-08-06 14:02:10.001",
    username: "Admin_01",
    role: "Admin",
    ip: "192.168.1.45",
    browser: "Chrome 122.0 / macOS",
    device: "MacBook Pro M3",
    action: "Accessed Client Profile",
    previousValue: "View State: List",
    newValue: "Opened Customer ID: CUST-1005 (Vikramaditya Rao)",
    riskTag: "LOW",
  },
  {
    id: "AUD-987",
    timestamp: "2026-08-06 13:55:44.320",
    username: "Ext_API_Gateway",
    role: "Employee",
    ip: "45.22.119.8",
    browser: "Python / FastAPI Service",
    device: "External Client Node",
    action: "Failed Authentication (x5)",
    previousValue: "Attempts: 0",
    newValue: "Attempts: 5 (Temporary IP Lockout 15m)",
    riskTag: "CRITICAL",
  },
];

export const initialEmployees: Employee[] = [
  {
    id: "EMP-101",
    empCode: "BG-ADM-01",
    name: "Vikramaditya Rao",
    email: "vikramaditya.rao@bankguard.ai",
    role: "Admin",
    department: "Executive Security & CISO",
    branchName: "Cyber City Main",
    status: "Active",
    joinedDate: "2021-03-15",
  },
  {
    id: "EMP-102",
    empCode: "BG-MGR-04",
    name: "Dr. Rajesh Mehta",
    email: "rajesh.mehta@bankguard.ai",
    role: "Manager",
    department: "SecOps Threat Intelligence",
    branchName: "BKC Financial Tower",
    status: "Active",
    joinedDate: "2022-08-01",
  },
  {
    id: "EMP-103",
    empCode: "BG-AUD-09",
    name: "Ayesha Patel",
    email: "ayesha.patel@bankguard.ai",
    role: "Auditor",
    department: "AML Risk & Compliance",
    branchName: "Cyber City Main",
    status: "Active",
    joinedDate: "2023-01-10",
  },
  {
    id: "EMP-104",
    empCode: "BG-CLK-12",
    name: "Devendra Kulkarni",
    email: "devendra.kulkarni@bankguard.ai",
    role: "Employee",
    department: "Customer Operations & Support",
    branchName: "Tech Park North",
    status: "Active",
    joinedDate: "2024-02-14",
  },
];

export const initialBranches: Branch[] = [
  {
    id: "BR-01",
    code: "BG-HYD-001",
    name: "Cyber City Main",
    managerName: "Vikramaditya Rao",
    address: "702 Jubilee Hills, Hyderabad, TS",
    customerCount: 8450,
    employeeCount: 42,
    atmCount: 12,
    monthlyRevenue: 1450000,
    performanceScore: 96,
    status: "Operational",
  },
  {
    id: "BR-02",
    code: "BG-KA-002",
    name: "Tech Park North",
    managerName: "Dr. Rajesh Mehta",
    address: "500 Whitefield Main Rd, Bengaluru, KA",
    customerCount: 6200,
    employeeCount: 28,
    atmCount: 8,
    monthlyRevenue: 980000,
    performanceScore: 91,
    status: "Operational",
  },
  {
    id: "BR-03",
    code: "BG-TN-003",
    name: "Downtown Central",
    managerName: "Ananya Gupta",
    address: "22 Anna Salai, Chennai, TN",
    customerCount: 5100,
    employeeCount: 22,
    atmCount: 6,
    monthlyRevenue: 820000,
    performanceScore: 88,
    status: "Operational",
  },
  {
    id: "BR-04",
    code: "BG-IN-004",
    name: "Cyber City West",
    managerName: "Vikram Mehta",
    address: "88 Tech Boulevard, Hyderabad, IN",
    customerCount: 4842,
    employeeCount: 19,
    atmCount: 5,
    monthlyRevenue: 650000,
    performanceScore: 84,
    status: "Operational",
  },
];

export const initialATMs: ATM[] = [
  {
    id: "ATM-101",
    code: "ATM-MUM-01",
    location: "BKC Metro Station Entrance, Mumbai",
    branchName: "BKC Financial District Main",
    status: "Online",
    cashRemaining: 84500,
    cashCapacity: 100000,
    lastSync: "10 mins ago",
    lastWithdrawalTime: "2 mins ago (₹200)",
    errorLogsCount: 0,
    recentLogs: ["08:00 Hardware Diagnostics Passed", "10:30 Dispenser Calibration OK"],
  },
  {
    id: "ATM-102",
    code: "ATM-MUM-02",
    location: "BKC West Hub, Mumbai",
    branchName: "BKC Financial District Main",
    status: "Low Cash",
    cashRemaining: 12400,
    cashCapacity: 100000,
    lastSync: "5 mins ago",
    lastWithdrawalTime: "1 min ago (₹500)",
    errorLogsCount: 1,
    recentLogs: ["09:45 Low Cash Warning Alert Triggered (12% remaining)"],
  },
  {
    id: "ATM-103",
    code: "ATM-BLR-04",
    location: "Bengaluru Tech Park Building 3 Lobby",
    branchName: "Tech Park North",
    status: "Offline",
    cashRemaining: 45000,
    cashCapacity: 80000,
    lastSync: "2 hours ago",
    lastWithdrawalTime: "2 hours ago (₹100)",
    errorLogsCount: 3,
    recentLogs: [
      "08:15 Connection Loss to Network Gateway",
      "08:30 Heartbeat Failed (3 Consecutive Timeouts)",
    ],
  },
  {
    id: "ATM-104",
    code: "ATM-CHE-02",
    location: "Chennai Central Terminal Mall",
    branchName: "Downtown Central",
    status: "Online",
    cashRemaining: 68000,
    cashCapacity: 90000,
    lastSync: "1 min ago",
    lastWithdrawalTime: "5 mins ago (₹300)",
    errorLogsCount: 0,
    recentLogs: ["10:15 Security Tamper Sensors Nominal"],
  },
];

export const initialLoans: Loan[] = [
  {
    id: "LN-8801",
    loanNumber: "LN-2025-8801",
    customerId: "CUST-1001",
    customerName: "Marcus Chen",
    loanType: "Home",
    amount: 450000,
    interestRate: 6.8,
    tenureMonths: 240,
    emiAmount: 3435,
    status: "Approved",
    creditScore: 785,
    riskAnalysis: "Low Risk - Strong asset backing & stable corporate income",
    appliedDate: "2025-01-15",
  },
  {
    id: "LN-8802",
    loanNumber: "LN-2025-8802",
    customerId: "CUST-1002",
    customerName: "Elena Jenkins",
    loanType: "Personal",
    amount: 35000,
    interestRate: 11.2,
    tenureMonths: 36,
    emiAmount: 1149,
    status: "Pending Approval",
    creditScore: 710,
    riskAnalysis: "Medium Risk - KYC pending verification",
    appliedDate: "2025-02-02",
  },
  {
    id: "LN-8803",
    loanNumber: "LN-2025-8803",
    customerId: "CUST-1004",
    customerName: "Priya Sharma",
    loanType: "Business",
    amount: 120000,
    interestRate: 9.5,
    tenureMonths: 60,
    emiAmount: 2521,
    status: "Approved",
    creditScore: 760,
    riskAnalysis: "Low Risk - Healthy business cash flow",
    appliedDate: "2025-01-28",
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: "NOTIF-1",
    title: "Critical Fraud Alert",
    message: "Multiple failed login attempts from IP 192.168.1.105 (Kolkata, WB) targeting account #5512-9901-8811.",
    type: "fraud",
    severity: "high",
    timestamp: "Just now",
    read: false,
  },
  {
    id: "NOTIF-2",
    title: "ATM Offline Alert",
    message: "ATM-BLR-04 (Bengaluru Tech Park Lobby) lost network connectivity. Maintenance dispatched.",
    type: "atm",
    severity: "medium",
    timestamp: "15 mins ago",
    read: false,
  },
  {
    id: "NOTIF-3",
    title: "High-Value Transfer Flagged",
    message: "Outbound transfer of ₹15,400 to Offshore Crypto Exchange placed on administrative hold.",
    type: "fraud",
    severity: "high",
    timestamp: "22 mins ago",
    read: false,
  },
  {
    id: "NOTIF-4",
    title: "Loan Approval Pending",
    message: "Personal loan application LN-2025-8802 (₹35,000) for Elena Jenkins requires manager signature.",
    type: "loan",
    severity: "info",
    timestamp: "1 hour ago",
    read: true,
  },
];

export const initialSupportTickets: SupportTicket[] = [
  {
    id: "ESC-8901",
    ticketNumber: "TKT-2026-001",
    senderName: "Ananya Sharma",
    senderRole: "Analyst",
    senderEmail: "ananya.sharma@bankguard.in",
    category: "Fraud Escalation",
    priority: "Urgent",
    relatedRef: "TX-9012",
    subject: "Rapid-Spike Velocity Transfer from Unverified Kolkata IP Node",
    message: "Detected 4 rapid consecutive transfers totaling ₹12,50,000 within 120 seconds targeting known mule account ACC-3304. Requesting immediate CISO freeze order.",
    attachLogs: true,
    status: "Pending Admin Review",
    timestamp: "10 minutes ago",
    adminReplies: [],
  },
  {
    id: "ESC-8902",
    ticketNumber: "TKT-2026-002",
    senderName: "Deepak Verma",
    senderRole: "Manager",
    senderEmail: "deepak.verma@bankguard.in",
    category: "Account Freeze Request",
    priority: "High",
    relatedRef: "ACC-5512",
    subject: "Aadhaar / PAN Identity Discrepancy on High-Balance Business Account",
    message: "Physical KYC document verification at Connaught Place branch failed biometric hash match against UIDAI database. Requesting admin locks on outgoing RTGS.",
    attachLogs: false,
    status: "In Investigation",
    timestamp: "42 minutes ago",
    adminReplies: [
      {
        id: "R1",
        sender: "Vikramaditya Rao (Admin / CISO)",
        text: "Account ACC-5512 placed on temporary 24-hour administrative hold. Audit team dispatched.",
        timestamp: "30 minutes ago",
      },
    ],
  },
  {
    id: "ESC-8903",
    ticketNumber: "TKT-2026-003",
    senderName: "Rohan Kulkarni",
    senderRole: "Auditor",
    senderEmail: "rohan.kulkarni@bankguard.in",
    category: "Model Retraining",
    priority: "Medium",
    relatedRef: "ML-RF-902",
    subject: "False Positive Spike on High-Volume Festive UPI Merchants",
    message: "Random Forest model flagging legitimate Diwali merchant UPI bursts. Suggest adjusting velocity weight threshold from 0.75 to 0.82.",
    attachLogs: true,
    status: "Resolved",
    timestamp: "2 hours ago",
    adminReplies: [
      {
        id: "R2",
        sender: "Vikramaditya Rao (Admin / CISO)",
        text: "Threshold updated in production ML pipeline. Telemetry re-evaluated.",
        timestamp: "1 hour ago",
      },
    ],
  },
];
